services:
  - type: web
    name: riad-api
    runtime: node
    rootDir: api
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
